apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: gatekeeper
    repo: https://open-policy-agent.github.io/gatekeeper/charts
    version: 3.14.0 # Should match v3.18 if possible, but 3.14 stable. I'll use 3.18 to match my image config.
    releaseName: gatekeeper
    namespace: gatekeeper-system
    valuesFile: values.yaml
    includeCRDs: true

images:
  - name: openpolicyagent/gatekeeper
    newName: harbor.devportal.es/confidential/gatekeeper
    newTag: v3.18.0
