[log]
level = "debug"

[shim]
agent_sock = "/run/rune/enclave-agent.sock"

[containerd]
agent_container_instance = "/opt/confidential-containers/share/enclave-cc-agent-instance"
agent_container_root_dir = "/run/containerd/agent-enclave"
boot_container_instance = "/opt/confidential-containers/share/enclave-cc-boot-instance"
