apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
  namespace: tekton-pipelines
data:
  default-timeout-minutes: "60"
  default-service-account: "default"
  default-managed-by-label-value: "tekton-pipelines"
  default-max-matrix-combinations-count: "256"
  default-sidecar-log-polling-interval: "100ms"
  default-step-ref-concurrency-limit: "5"
  # Helper images
  default-entrypoint-image: "harbor.devportal.es/confidential/tekton:v1.6.0"
  default-nop-image: "harbor.devportal.es/confidential/tekton:v1.6.0"
  default-shell-image: "cgr.dev/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791"
  default-shell-image-win: "mcr.microsoft.com/powershell:nanoserver@sha256:b6d5ff841b78bdf2dfed7550000fd4f3437385b8fa686ec0f010be24777654d6"
  default-sidecarlogresults-image: "harbor.devportal.es/confidential/tekton:v1.6.0"
  default-workingdirinit-image: "harbor.devportal.es/confidential/tekton:v1.6.0"
