apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: tetragon
    repo: https://helm.cilium.io/
    version: 1.6.0
    releaseName: tetragon
    namespace: tetragon
    valuesFile: values.yaml
    includeCRDs: true

images:
  - name: quay.io/cilium/tetragon
    newName: local/tetragon
    newTag: v1.6.0

patchesStrategicMerge:
  - patch-ds.yaml
