apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: keptn
    repo: https://charts.lifecycle.keptn.sh
    version: 0.11.0 # Using latest valid chart version
    releaseName: keptn
    namespace: keptn-system
    valuesFile: values.yaml
    includeCRDs: true

images:
  - name: keptn/lifecycle-operator
    newName: harbor.devportal.es/confidential/keptn-operator
    newTag: v1.1.1
